# Camera

CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
DISPLAY_FLIP = True
DISPLAY_WINDOW_NAME = 'Gesture Control System'

# MediaPipe

MP_MAX_HANDS = 1
MP_DETECTION_CONFIDENCE = 0.85
MP_TRACKING_CONFIDENCE = 0.85

# FPS counter

FPS_SMOOTHING = 10

# Colors

COLOR_NEON_GREEN = (0, 255, 0)
COLOR_NEON_CYAN = (255, 220, 0)
COLOR_NEON_PURPLE = (200, 50, 220)

COLOR_OVERLAY_BG = (10, 10, 20)

# Landmark drawing

LANDMARK_RADIUS = 5
LANDMARK_COLOR = COLOR_NEON_GREEN
CONNECTION_COLOR = COLOR_NEON_CYAN
CONNECTION_THICKNESS = 2

# Text

FONT = 0
FONT_SCALE_SMALL = 0.55
FONT_SCALE_MEDIUM = 0.75
FONT_THICKNESS = 2

# Mouse

MOUSE_SMOOTHING_FACTOR = 0.07
MOUSE_MARGIN = 120
CLICK_COOLDOWN_MS = 350